# Generated by Django 4.2.7 on 2024-01-29 11:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_alter_friendship_followed_alter_friendship_follower_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.upload_user_avatar
            ),
        ),
    ]
