# Generated by Django 4.2.7 on 2023-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_conversation_id_alter_conversationmessage_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="modefied_at",
            new_name="modified_at",
        ),
    ]
