# Generated by Django 4.2.7 on 2023-12-12 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_modefied_at_conversation_modified_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ("-modified_at",)},
        ),
    ]
