# Generated by Django 4.2.7 on 2023-11-26 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_comment_post_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
    ]
