# Generated by Django 4.2.7 on 2023-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="posts.post"
            ),
        ),
    ]
